### ISSUE TITLE
Installing Maiden on CentOs 6

### ISSUE THREAD

**Issue by stevenjack** [serby/maiden#7]
Hey Paul,

Just wondering if you had any insight into why I would be getting the following:

Fatal error: Exception thrown without a stack frame in Unknown on line 0

When trying to run the last last part of the installation:

./maiden install

I'm running CentOs 6 and php version 5.3.2 if that helps...

Thanks,

Steven

**Comment by serby** [comment]
Thanks Steven

I think I have an idea what causes this.

I'll get back to you shortly.

Regards

Paul

**Comment by serby** [comment]
It might be an error with the exception handler.

Can you give me a login to the machine?

This is my public key

ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEA452qQA0DnG1Yf1YKjZQLJoohbcnAt8OCgkyz2YwhrFHp4+eNvEnZYgEnHhDDITHKV0l0BcuQL1ELVHIXDFl+Dm3cFsAe/vVqfEodlLtU2C/35lqiXzUGxx0XkZFttzk9cnJC925rk4ESJU1P9W8qykGLC6NB5gV6rTCvCraJOes= Paul Serby

**Comment by stevenjack** [comment]
Hey Paul,

login is:

paul@78.129.247.241

you have root privs on it, it's only a VM with no production sites on it at the moment so don't worry about messing anything up :).

Thanks for looking into this!

Steve

**Comment by serby** [comment]
Just hanging when try ssh and can't ping. Any ideas?

On 30 September 2011 16:15, Steven Jack
reply@reply.github.com
wrote:

> Hey Paul,
> 
> login is:
> 
> paul@78.129.247.241
> 
> you have root privs on it, it's only a VM with no production sites on it at the moment so don't worry about messing anything up :).
> 
> Thanks for looking into this!
> 
> Steve
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/PabloSerbo/maiden/issues/7#issuecomment-2250614

## 

paul.serby@clock.co.uk
Chief Technology Officer

Direct: +44 2030 516115
Mobile: +44 7881 550999
Conference: +44 20 3051 6144

Clock Limited
The Old School House
Bridge Road, Hunton Bridge,
Kings Langley, WD4 8RQ
Switchboard: +44 1923 261166

www.clock.co.uk

http://twitter.com/clock
http://blog.clock.co.uk/
http://delicious.com/clocklimited

www.clock.co.uk/email-disclaimer

clock.® is a Registered Trademark of Clock Limited in the European
Community and other territories

**Comment by stevenjack** [comment]
Sorry Paul,

Just realised I had ssh locked down to our office ip, I'll drop the firewall for the moment.

Steve

**Comment by serby** [comment]
To fix your problem you need to set a timezone in your php.ini.

I will also fix maiden to show better errors.

There reason your error message was unhelpful was because it was triggered in the exception handler.

**Comment by serby** [comment]
Timezone now defaults to UTC to suppress the error
