### ISSUE TITLE
MaidenClockCommon: Symlink must not be updated until end of install

### ISSUE THREAD

**Issue by robnoake** [serby/maiden#9]
When deploying a project, the symlink to the target directory is removed prior to the setupFolder and updateDatabase steps. 

This is causing sites with front-end caches to 503 while updateDatabase is running, and requires manual intervention to restore the production symlink in cases where updateDatabase causes the build process to fail.

**Comment by serby** [comment]
Been fixed in a update from Luke 53d14c3a4a37bbafe60a76f445a4f145f2f46bfe

This now merged

**Comment by robnoake** [comment]
Thanks!
